### ISSUE TITLE
Multiple dispatch TODO list:

### ISSUE THREAD

**Issue by davisyoshida** [davisyoshida/qax#3]
Issue for tracking investigation of switching to multiple dispatch instead of handler methods.

I have an initial implementation using Plum for multiple dispatch on the multiple-dispatch branch. The examples are updated, e.g. [zero.py](https://github.com/davisyoshida/qax/blob/multiple-dispatch/examples/zero.py).

I'll update this with things I need to figure out/problems as they come up.

TODO/things to figure out:
- [x] Figure out what to do about heterogenous inputs. Currently all but those sharing the type of the leftmost implicit argument are materialized, but obviously a benefit of multiple dispatch would be defining behavior for mixed types. On the other hand, if such a handler _isn't_ defined, I don't want to just materialize all the arguments, so there needs to be a graceful fallback.
- [x] Related: If a specific handler returns NotImplemented, it would be nice to try the next-most specific handler rather than falling all the way back to the default handler.
- [x] I'm manually handling the dispatching in qax/primitives.py so that overrides will be registered against actual jax.core.Primitive instances rather than function string names. Need to decide if this is ideal.
- [x] Registering handlers with strings uses getattr against jax.lax to look for `f'{name}_p'`. This makes it really convenient but may have some failure mode I haven't thought of
- [x] What should be done in the case of primitives which have a variable number of arguments?

**Comment by davisyoshida** [comment]
@patrick-kidger I'm trying Plum out if you want to take a look at the example or comment on any of these points. I haven't used Plum before so I'm a bit worried there will be sharp edges I'm unaware of.

**Comment by patrick-kidger** [comment]
> Figure out what to do about heterogenous inputs. Currently all but those sharing the type of the leftmost implicit argument are materialized, but obviously a benefit of multiple dispatch would be defining behavior for mixed types. On the other hand, if such a handler isn't defined, I don't want to just materialize all the arguments, so there needs to be a graceful fallback.

I think "materialise everything" is probably a good fallback. A type's materialise rule can always be to raise an error or warning if needed. 

> Related: If a specific handler returns NotImplemented, it would be nice to try the next-most specific handler rather than falling all the way back to the default handler.

I'm not sure how frequently this comes up -- what's your use case? Usually I'd think of each handler knowing precisely what to do.

(I.e. I think even falling all the way back to the default handled sounds wrong -- once you've picked a dispatch rule there shouldn't be any fallback at all.)

> Registering handlers with strings uses getattr against jax.lax to look for f'{name}_p'. This makes it really convenient but may have some failure mode I haven't thought of

Many primitives are not defined in `lax`, e.g. custom user primitives. (And many in core JAX too.)

> What should be done in the case of primitives which have a variable number of arguments?

Something like
```python
@register
def concatenate(*args: ZeroArrayValue):
    return Zero(shape=... dtype=...)

@register
def concatenate(*args: ArrayValue):
    args = tuple(materialise(x) for x in args)
    ...  # default
```
?
Here `concatenate(zero, array)` will hit the second one, according to subclassing rules.

> I haven't used Plum before so I'm a bit worried there will be sharp edges I'm unaware of.

I think the main one is using precedence to avoid ambiguity: https://beartype.github.io/plum/precedence.html

Also, as a general principle: I think the types being dispatched on should be organised into a class hierarchy, with every type being precisely one of (a) abstract or (b) final.

E.g. in my above example I introduced `ArrayValue` and `ZeroArrayValue`. The overall hierarchy would be `ZeroArrayValue <: ArrayValue <: Value` and `DenseArrayValue <: ArrayValue`, where `DenseArrayValue` denotes the default dense JAX array.

**Comment by davisyoshida** [comment]
> Many primitives are not defined in lax, e.g. custom user primitives. (And many in core JAX too.)

Yeah what I went with was you can point at the ones in LAX with strings but for other ones you'll need to pass the actual primitive.

> I'm not sure how frequently this comes up -- what's your use case? Usually I'd think of each handler knowing precisely what to do.

In my LoRA transform I have it only handling gather if the params satisfy certain requirements, and using the default behavior otherwise. I don't really have a use case for falling back to intermediate ones though so I'll probably just leave it as is.

Re: variadic primitives, it seems like a pretty common case would be only one of many inputs being an ImplicitArray. It's probably fine for a user defined handler to figure out what to do in that case. I don't know what the full set of variadic primitives is, so I'm not sure how much I need to worry about this.

>  the types being dispatched on should be organised into a class hierarchy

This is reasonable, so I guess I'll need to add a common ancestor for jax.Array and ImplicitArray.

**Comment by patrick-kidger** [comment]
> In my LoRA transform I have it only handling gather if the params satisfy certain requirements, and using the default behavior otherwise. I don't really have a use case for falling back to intermediate ones though so I'll probably just leave it as is.

This is an interesting point. I'd suggest opening it as a request on the plum issue tracker.

> This is reasonable, so I guess I'll need to add a common ancestor for jax.Array and ImplicitArray.

Preferring composition over inheritance -- I'm guessing this might be easier using newly-introduced types instead; stored as extra metadata on the tracer.

**Comment by davisyoshida** [comment]
>Preferring composition over inheritance -- I'm guessing this might be easier using newly-introduced types instead; stored as extra metadata on the tracer.

Well I just meant registering an ABC for the type annotations, not necessarily making a new class. I definitely don't want to mess around with actually inheriting from jax.Array.

As for the tracer thing I'm not quite sure what you mean. Currently the values are unboxed out of tracers prior to invocation of the handler. Right now those values will either be an ImplicitArray instance or a JAX value.
